Repository nqminds/edgesec, pull requests merged in 2022-11, with the labels that each got.

#331 Allow using existing `libprotobuf-c` library
  CMakeModules/FindProtobufC.cmake
  debian/control
  debian/rules
  lib/protobuf-c.cmake
  src/capture/CMakeLists.txt
  src/capture/middlewares/protobuf_middleware/CMakeLists.txt
  tests/capture/middlewares/CMakeLists.txt
Labels: dependencies

#332 Fix failing `cmocka` build, due to upstream bug
  CMakePresets.json
  lib/cmocka.cmake
Labels: bug, dependencies

#334 Use `AddCMockaTest.cmake` script to simplify test scripts
  CMakeLists.txt
  CMakeModules/AddCMockaTest.cmake
  debian/copyright
  tests/CMakeLists.txt
  tests/ap/CMakeLists.txt
  tests/capture/CMakeLists.txt
  tests/capture/middlewares/CMakeLists.txt
  tests/crypt/CMakeLists.txt
  tests/dhcp/CMakeLists.txt
  tests/dns/CMakeLists.txt
  tests/radius/CMakeLists.txt
  tests/supervisor/CMakeLists.txt
  tests/system/CMakeLists.txt
  tests/utils/CMakeLists.txt
Labels: refactor

#337 docs(lib/cmocka.cmake): document licensing info
  debian/copyright
Labels: documentation

#336 docs(radius_client): document licensing info
  debian/copyright
Labels: documentation

#338 Download ExternalProject files into `EP_DOWNLOAD_DIR`
  CMakeLists.txt
  CMakeModules/CMakeToolchains/DefineOpenWRTSDKToolchain.cmake
  CMakePresets.json
  lib/cmocka.cmake
  lib/hostapd.cmake
  lib/mnl.cmake
  lib/openssl.cmake
  lib/pcap.cmake
  lib/sqlite.cmake
  lib/uci.cmake
  lib/uthash.cmake
  lib/uuid.cmake
Labels: dependencies

#340 refactor(squeue): cleanup squeue includes
  src/utils/CMakeLists.txt
  src/utils/squeue.c
  src/utils/squeue.h
  tests/utils/test_squeue.c
Labels: refactor

#341 Support compiling edgesec using standard ISO C11
  CMakeModules/FindPCAP.cmake
  lib/libnetlink/CMakeLists.txt
  lib/netlink.cmake
  lib/pcap.cmake
  lib/uthash.cmake
  src/ap/ap_config.h
  src/capture/capture_service.c
  src/capture/capture_service.h
  src/capture/middlewares/header_middleware/packet_decoder.c
  src/capture/middlewares/header_middleware/packet_decoder.h
  src/capture/pcap_service.c
  src/capture/pcap_service.h
  src/config.c
  src/config.h
  src/dhcp/dhcp_config.h
  src/dhcp/dnsmasq.c
  src/dhcp/dnsmasq.h
  src/dns/CMakeLists.txt
  src/dns/reflection_list.c
  src/dns/reflection_list.h
  src/firewall/firewall_service.c
  src/radius/CMakeLists.txt
  src/runctl.c
  src/supervisor/mac_mapper.c
  src/supervisor/mac_mapper.h
  src/supervisor/network_commands.c
  src/supervisor/supervisor_config.h
  src/supervisor/system_commands.c
  src/utils/CMakeLists.txt
  src/utils/iface_mapper.c
  src/utils/iface_mapper.h
  src/utils/iptables.c
  src/utils/list.h
  src/utils/nl.c
  src/utils/nl.h
  src/utils/os.h
  src/utils/squeue.h
  tests/radius/CMakeLists.txt
  tests/utils/CMakeLists.txt
Labels: refactor

#315 refactor(squeue): make squeue params const
  src/utils/squeue.c
  src/utils/squeue.h
Labels: documentation, refactor

#348 Use SQLITE transactions when inserting PCAP data in `recap`.
  CMakeLists.txt
  src/CMakeLists.txt
  src/recap.c
  tests/CMakeLists.txt
  tests/data/test.pcap
Labels: refactor

#349 Continuous pcap stream integration
  src/CMakeLists.txt
  src/capture/middlewares/header_middleware/header_middleware.c
  src/capture/middlewares/header_middleware/packet_decoder.c
  src/capture/middlewares/header_middleware/packet_decoder.h
  src/capture/middlewares/protobuf_middleware/protobuf_middleware.c
  src/capture/middlewares/protobuf_middleware/protobuf_middleware.h
  src/capture/pcap_service.c
  src/capture/pcap_service.h
  src/dns/mdns_service.c
  src/dns/mdns_service.h
  src/recap.c
  tests/CMakeLists.txt
Labels: enhancement
