Repository nqminds/edgesec, pull requests merged in 2022-09, with the labels that each got.

#240 build(debian): link to sqlite3/libpcap shared libs
  CMakeLists.txt
  debian/control
  debian/rules
  lib/pcap.cmake
  lib/sqlite.cmake
  src/CMakeLists.txt
  src/capture/CMakeLists.txt
  src/capture/capture_service.c
  src/config.c
  src/dns/CMakeLists.txt
  src/edgesec.c
  tests/capture/middlewares/CMakeLists.txt
  tests/dhcp/test_dhcp_service.c
  tests/dhcp/test_dnsmasq.c
  tests/dns/test_command_mapper.c
  tests/dns/test_mdns_list.c
  tests/dns/test_mdns_mapper.c
  tests/dns/test_mdns_service.c
  tests/dns/test_reflection_list.c
  tests/utils/CMakeLists.txt
Labels: dependencies

#241 docs: add a "code-style LLVM" badge
  README.md
Labels: documentation

#249 refactor: remove linux/types.h and posix_types.h
  src/radius/radius.h
  src/radius/radius_server.c
  src/radius/radius_server.h
  src/radius/wpabuf.h
  tests/radius/ip_addr.h
  tests/radius/radius_client.c
  tests/radius/radius_client.h
  tests/radius/test_radius_server.c
Labels: refactor

#251 test: fix undeclared identifier AF_INET
  tests/radius/ip_addr.c
Labels: bug

#237 Fix some bugs in `list_dir`
  src/utils/os.c
  src/utils/os.h
  tests/utils/test_os.c
Labels: bug

#246 refactor: replace <linux/if.h> with <net/if.h>
  src/ap/ap_config.h
  src/capture/capture_service.c
  src/capture/middlewares/header_middleware/dns_decoder.c
  src/capture/middlewares/header_middleware/mdns_decoder.c
  src/capture/middlewares/header_middleware/packet_decoder.c
  src/capture/middlewares/header_middleware/packet_decoder.h
  src/capture/pcap_service.c
  src/capture/pcap_service.h
  src/dhcp/dhcp_config.h
  src/dns/reflection_list.h
  src/edgesec.c
  src/radius/radius_server.c
  src/runctl.h
  src/utils/iface.c
  src/utils/iface.h
  src/utils/iface_mapper.c
  src/utils/iface_mapper.h
  src/utils/ifaceu.c
  src/utils/net.c
  src/utils/net.h
  src/utils/nl.c
  src/utils/nl.h
  tests/dhcp/test_dhcp_service.c
  tests/dhcp/test_dnsmasq.c
  tests/dns/test_command_mapper.c
  tests/dns/test_mdns_list.c
  tests/dns/test_mdns_mapper.c
  tests/dns/test_mdns_service.c
  tests/dns/test_reflection_list.c
  tests/radius/ip_addr.h
  tests/radius/radius_client.c
  tests/radius/radius_client.h
  tests/radius/test_radius_server.c
Labels: refactor

#239 refactor: fix const char * warnings
  src/utils/net.c
  src/utils/net.h
  src/utils/nl.c
  src/utils/nl.h
  tests/utils/CMakeLists.txt
  tests/utils/test_nl.c
  tests/utils/test_wrap_log_error.c
  tests/utils/wrap_log_error.c
  tests/utils/wrap_log_error.h
Labels: refactor

#247 refactor: remove `#include <linux/if_link.h>`
  src/utils/iface.c
Labels: refactor

#248 refactor: replace ETH_ALEN with ETHER_ADDR_LEN
  src/ap/ap_service.c
  src/capture/middlewares/header_middleware/dns_decoder.c
  src/capture/middlewares/header_middleware/mdns_decoder.c
  src/capture/middlewares/header_middleware/packet_decoder.c
  src/capture/middlewares/header_middleware/packet_decoder.h
  src/radius/radius_server.c
  src/radius/radius_server.h
  src/supervisor/bridge_list.c
  src/supervisor/bridge_list.h
  src/supervisor/cmd_processor.c
  src/supervisor/mac_mapper.c
  src/supervisor/mac_mapper.h
  src/supervisor/network_commands.c
  src/supervisor/sqlite_macconn_writer.c
  src/supervisor/supervisor.c
  src/supervisor/system_commands.c
  src/utils/iface_mapper.h
  src/utils/net.c
  src/utils/net.h
  src/utils/nl.c
  src/utils/nl.h
  tests/radius/radius_client.c
  tests/supervisor/test_bridge_list.c
  tests/supervisor/test_cmd_processor.c
  tests/supervisor/test_sqlite_macconn_writer.c
Labels: refactor

#254 ci: fix intermittent disk I/O error
  .github/workflows/create-debs.yml
Labels: bug

#255 refactor: remove unnecessary middlewares includes
  src/capture/middlewares/header_middleware/dns_decoder.c
  src/capture/middlewares/header_middleware/mdns_decoder.c
  src/capture/middlewares/header_middleware/packet_decoder.c
  src/capture/middlewares/header_middleware/packet_decoder.h
Labels: refactor

#256 refactor: remove `#include <asm/types.h>`
  src/radius/radius.h
  src/radius/radius_server.c
  src/radius/radius_server.h
  tests/radius/ip_addr.h
  tests/radius/radius_client.c
  tests/radius/radius_client.h
  tests/radius/test_radius_server.c
Labels: refactor

#257 refactor: add #include <stdint.h> before cmocka
  tests/ap/test_ap_service.c
  tests/ap/test_hostapd.c
  tests/capture/middlewares/test_header_middleware.c
  tests/capture/middlewares/test_packet_queue.c
  tests/capture/middlewares/test_pcap_queue.c
  tests/capture/middlewares/test_sqlite_header.c
  tests/capture/middlewares/test_sqlite_pcap.c
  tests/capture/test_capture_service.c
  tests/crypt/test_crypt_service.c
  tests/crypt/test_sqlite_crypt_writer.c
  tests/dhcp/test_dhcp_service.c
  tests/dhcp/test_dnsmasq.c
  tests/dns/test_command_mapper.c
  tests/dns/test_mdns_list.c
  tests/dns/test_mdns_mapper.c
  tests/dns/test_mdns_service.c
  tests/dns/test_reflection_list.c
  tests/radius/test_radius_server.c
  tests/supervisor/test_bridge_list.c
  tests/supervisor/test_cmd_processor.c
  tests/supervisor/test_mac_mapper.c
  tests/supervisor/test_sockctl_server.c
  tests/supervisor/test_sqlite_macconn_writer.c
  tests/system/test_system_checks.c
  tests/test_runctl.c
  tests/utils/test_hashmap.c
  tests/utils/test_iface_mapper.c
  tests/utils/test_ifaceu.c
  tests/utils/test_minIni.c
  tests/utils/test_net.c
  tests/utils/test_nl.c
  tests/utils/test_os.c
  tests/utils/test_sqliteu.c
  tests/utils/test_squeue.c
  tests/utils/test_uci_wrt.c
  tests/utils/test_utarray.c
  tests/utils/test_wrap_log_error.c
  tests/utils/wrap_log_error.c
Labels: refactor

#258 build: bump cmocka to latest master commit
  lib/cmocka.cmake
Labels: dependencies

#260 test: remove incorrect error_t type
  tests/dhcp/test_dnsmasq.c
Labels: bug

#259 refactor(wpabuf): simplify byte swaps
  src/radius/wpabuf.h
Labels: refactor

#261 refactor: use POSIX standard udphdr/tcphdr
  src/capture/middlewares/header_middleware/packet_decoder.c
Labels: refactor

#262 refactor: include sys/socket.h then netinet/in.h
  .clang-format
  src/radius/radius_server.h
  tests/radius/radius_client.c
Labels: refactor

#268 refactor(nl): mark subnet_mask param as const
  src/utils/nl.c
  src/utils/nl.h
Labels: refactor

#269 fix(dnsmasq): truncate interface names/prefix
  src/dhcp/dnsmasq.c
  src/dhcp/dnsmasq.h
  tests/dhcp/test_dnsmasq.c
Labels: bug

#272 test(os): standardize test_run_command test
  tests/utils/test_os.c
Labels: bug

#270 docs: optimize doxygen docs for C code
  docs/doxygen.cmake
Labels: documentation

#271 Improve the GitHub Actions cache step
  .github/workflows/create-debs.yml
Labels: bug

#264 Recap
  .vscode/settings.json
  CMakePresets.json
  src/CMakeLists.txt
  src/capture/middleware.h
  src/capture/middlewares/header_middleware/header_middleware.c
  src/capture/middlewares/header_middleware/packet_decoder.c
  src/capture/middlewares/header_middleware/packet_decoder.h
  src/edgesec.c
  src/recap.c
  src/utils/eloop.h
Labels: enhancement

#274 refactor(sockctl): make data param `const`
  src/utils/sockctl.c
  src/utils/sockctl.h
Labels: refactor

#168 fix: create folders for SQLite macconn_db
  src/supervisor/sqlite_macconn_writer.c
  src/supervisor/sqlite_macconn_writer.h
Labels: bug

#276 Cleanup sockctl tests
  tests/supervisor/test_sockctl_server.c
Labels: refactor

#275 Eloop test
  .vscode/settings.json
  tests/utils/CMakeLists.txt
  tests/utils/test_eloop.c
  tests/utils/test_eloop_threaded.c
Labels: refactor

#279 Standardise `test_run_commands` test
  src/utils/os.h
  tests/utils/test_os.c
Labels: refactor

#280 refactor(middlewares): fix const stype difference
  src/capture/middlewares/cleaner_middleware/cleaner_middleware.c
  src/capture/middlewares/pcap_middleware/pcap_middleware.c
Labels: refactor

#283 refactor(radius_client): fix ptr to enum cast
  tests/radius/radius_client.c
Labels: refactor

#282 test(os): fix broken make_dirs_to_path teardown
  tests/utils/test_os.c
Labels: bug

#284 test(packet_queue): fix uninitialised warning
  tests/capture/middlewares/test_packet_queue.c
Labels: refactor

#285 fix(nl): fix missing curly brackets
  src/utils/nl.c
Labels: bug

#281 feat(os): add copy_argv() function
  src/utils/os.c
  src/utils/os.h
  tests/utils/test_os.c
Labels: enhancement, refactor

#278 Add fallback for unsupported abstract sockets
  src/ap/ap_service.c
  src/dns/mdns_service.c
  src/utils/CMakeLists.txt
  src/utils/sockctl.c
  src/utils/sockctl.h
  tests/supervisor/CMakeLists.txt
  tests/supervisor/test_sockctl_server.c
Labels: bug

#289 fix(nl): fix potential missing NUL terminator
  src/utils/nl.c
Labels: bug

#290 refactor(sockctl): store tmp sock in /tmp/edgesec
  src/utils/sockctl.c
Labels: refactor

#292 Error on all C/C++ compiler warnings in `src/` and `tests/`
  src/CMakeLists.txt
  tests/CMakeLists.txt
  tests/utils/test_os.c
Labels: enhancement

#291 fix(sockctl): fix cleanup of unix mkdtemp dirs
  src/utils/sockctl.c
Labels: bug

#293 Replace pthread with threads in `test_eloop_threaded`
  CMakeLists.txt
  tests/utils/test_eloop_threaded.c
Labels: refactor

#295 docs: link to cppreference.com in doxygen docs
  docs/doxygen-tag-files.cmake
  docs/doxygen.cmake
Labels: documentation

#296 Remove deprecated `tempnam()` from eloop tests
  tests/utils/CMakeLists.txt
  tests/utils/test_eloop.c
  tests/utils/test_os.c
  tests/utils/tmpdir.c
  tests/utils/tmpdir.h
Labels: refactor

#298 refactor(log): delete `ename.h` header
  src/utils/ename.h
  src/utils/log.c
  tests/utils/test_log_err.c
Labels: refactor

#304 Add `const` to some often used functions
  src/firewall/firewall_service.c
  src/utils/iptables.c
  src/utils/os.c
  src/utils/os.h
Labels: refactor
