Repository nqminds/edgesec, pull requests merged in 2022-10, with the labels that each got.

#305 Download `minIni` instead of embedding source in repo
  CMakeLists.txt
  CMakeModules/FindMinIni.cmake
  debian/control
  debian/copyright
  debian/rules
  lib/minIni.cmake
  src/CMakeLists.txt
  src/capture/CMakeLists.txt
  src/config.c
  src/edgesec.c
  src/utils/CMakeLists.txt
  src/utils/minGlue.h
  src/utils/minIni.c
  src/utils/minIni.h
  tests/utils/CMakeLists.txt
  tests/utils/test_minIni.c
Labels: refactor, dependencies

#306 Fix string bug in run dhcp process
  src/dhcp/dnsmasq.c
  src/dhcp/dnsmasq.h
  src/utils/os.h
Labels: bug, refactor

#307 Refactor non-`const` string literals in `iptables`
  src/utils/iptables.c
  src/utils/iptables.h
  src/utils/net.c
  src/utils/net.h
Labels: refactor

#308 Fix string bug in hostapd
  src/ap/hostapd.c
  src/ap/hostapd.h
Labels: bug

#309 refactor(radius): fix `-Wwrite-strings`
  src/radius/radius.c
Labels: refactor

#311 Make `hmap_str_keychar_get()` params const
  src/firewall/firewall_service.c
  src/runctl.c
  src/utils/hashmap.c
  src/utils/hashmap.h
  src/utils/iptables.c
  src/utils/iptables.h
  tests/system/test_system_checks.c
  tests/test_runctl.c
  tests/utils/test_hashmap.c
Labels: refactor

#312 Cleanup sockctl files
  src/utils/net.c
  src/utils/net.h
  src/utils/sockctl.c
  src/utils/sockctl.h
Labels: bug, refactor

#316 Test the IP_GENERIC_SERVICE using GitHub Actions
  .github/workflows/create-debs.yml
  CMakePresets.json
  src/utils/ipgen.c
  src/utils/ipgen.h
Labels: bug, enhancement

#318 Prevent modifying string literals in `runctl`
  src/runctl.c
  src/utils/hashmap.c
  src/utils/hashmap.h
  src/utils/os.c
  src/utils/os.h
Labels: bug, refactor

#319 Argv
  src/capture/middlewares/header_middleware/dns_decoder.c
  src/recap.c
  tests/capture/middlewares/test_sqlite_header.c
Labels: hacktoberfest-accepted

#320 refactor(uci_wrt): fix `-Wwrite-string` warnings
  src/utils/uci_wrt.c
Labels: refactor

#321 Fix `linux-with-crypt` `-Wwrite-string` warnings
  src/crypt/crypt_service.c
  src/crypt/crypt_service.h
  src/crypt/sqlite_crypt_writer.c
  src/crypt/sqlite_crypt_writer.h
  src/utils/cryptou.c
  src/utils/cryptou.h
Labels: refactor

#322 refactor(eloop): remove `eloop_wait_for_read_sock`
  src/utils/eloop.c
  src/utils/eloop.h
Labels: refactor

#324 Optimize the `hash` library
  src/utils/CMakeLists.txt
  src/utils/hash.c
  src/utils/hash.h
Labels: refactor

#325 nl and net const improvements
  src/utils/net.c
  src/utils/net.h
  src/utils/nl.c
  src/utils/nl.h
Labels: refactor
